# Generated by Django 4.0.6 on 2022-08-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_enregable_estudiante_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enregable',
            new_name='Entregable',
        ),
    ]
